# Generated by Django 4.0.5 on 2022-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0002_remove_post_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='../app_proyecto/static/app_proyecto/assets/img/usuario.jpg', null=True, upload_to='avatares'),
        ),
    ]
